# Generated by Django 3.0.3 on 2020-02-09 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200209_1823'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='pokeapi_url',
            field=models.URLField(default='cake'),
            preserve_default=False,
        ),
    ]
